name: MaylanMarkers
version: ${version}
main: dev.deimoslabs.easysignmarkers.SignMarkers
api-version: '26.1.2'
folia-supported: true
authors: [kugge, deimiczny, jeffors, maylan-craft]
depend: [BlueMap]
description: Easily add markers to BlueMap with in-game signs
